-- Add V4 activity types to PostgreSQL enum
DO $$ BEGIN
  ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'KARTING';
  ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'REALITE_VIRTUELLE';
  ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'QUIZ_GAME';
  ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'MINIGOLF';
  ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ESCALADE';
  ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'PATINOIRE';
  ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'SPA_BIEN_ETRE';
  ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ATELIER';
  ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'DEGUSTATION';
  ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'COMEDY_CLUB';
  ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'MUSEE_EXPO';
  ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'CONCERT_SPECTACLE';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
